### ISSUE TITLE
RES generators in the sea (not wind offshore)

### ISSUE THREAD

**Issue by gplssm** [openego/data_processing#176] opened 2017-09-22 14:50 UTC
I already reported to @wolfbunke via telephone and mail. Around Helgoland, some PV power plants are located in the sea. 
![res_powerplant_in_the_sea](https://user-images.githubusercontent.com/8255114/30750200-0c41d430-9fb6-11e7-8714-3ad821908139.jpeg)

Can you say something about the progress?

**Comment by wolfbunke** [comment] 2017-09-25 08:03
Hey @gplssm are you using the sq_MView here?

**Comment by gplssm** [comment] 2017-09-25 14:05
Nope, this is based on v0.2.10. I haven't checked the data of version 0.3.0 for this issue. Do you know if the same issue occurs there as well?

**Comment by wolfbunke** [comment] 2017-09-26 10:48
ok, I will check it.

**Comment by wolfbunke** [comment] 2017-10-06 11:45
I was testing the table:
- supply.ego_dp_res_powerplant
- model_draft.ego_dp_supply_res_powerplant
- model_draft.ego_supply_res_powerplant

and could not reproduce your data error. Can you please name me the schema and name of the table which shows this error?

**Comment by gplssm** [comment] 2017-10-06 13:55
Please take data of
```
SELECT *
  FROM supply.ego_dp_res_powerplant
  WHERE version = 'v0.2.10'
  AND voltage_level >= 4;
```

Put a map in the background a look north of Helgoland. There are two wind offshore power plants (in and close to "Danger Area Sylt A" that are connected in Ding0 to the MV grid. These wind power plants are tagged with voltage_level 4/5.
Thus, I would say the position of the power plants is fine, but voltage level assignment is wrong.

I thought that I found a PV power plant located in the sea last time, but I cannot find it anymore....

**Comment by wolfbunke** [comment] 2017-10-06 14:21
ok, thanks, I will take a closer look and control all wind_offshore plants according to there voltage level.  By my visual check with QGIS I cound't find this PV units either.

**Comment by wolfbunke** [comment] 2017-10-06 14:35
Looks like between the versions there are few changes and maybe script parts got lost:

```
SELECT generation_subtype,voltage_level, count(*), version
  FROM supply.ego_dp_res_powerplant
  Where generation_subtype = 'wind_offshore'
Group by voltage_level,generation_subtype,version
Order by voltage_level,version
```
|generation_subtype|voltage_level|count(*)| version|
|--------|----|-----|-------|
|wind_offshore|1|1104|v0.2.10|
|wind_offshore|1|1321|v0.2.8|
|wind_offshore|1|1104|v0.2.9|
|wind_offshore|3|9|v0.2.10|
|wind_offshore|3|3|v0.2.8|
|wind_offshore|3|9|v0.2.9|
|wind_offshore|4|113|v0.2.10|
|wind_offshore|4|113|v0.2.9|
|wind_offshore|5|99|v0.2.10|
|wind_offshore|5|1|v0.2.8|
|wind_offshore|5|99|v0.2.9|

|total|version|
|-------|-----|
|1325|v0.2.10|
|1325|v0.2.9|
|1325|v0.2.8|

**Comment by gplssm** [comment] 2017-10-06 14:52
Thanks for diggin'! If only wind offshore PPs are located in the sea, I'm in general fine with it. The only that has to be changed is the voltage level. Offshore wind PP can not have voltage level >= 4.

**Comment by wolfbunke** [comment] 2017-10-17 12:48
This was an error of the first versions.
In the next version with can be found in model_draft it is fixed. See:
```
SELECT generation_subtype,voltage_level, count(*), preversion
  FROM model_draft.ego_dp_supply_res_powerplant
  Where generation_subtype = 'wind_offshore'
Group by voltage_level,generation_subtype,preversion
Order by voltage_level,preversion
```

**Comment by wolfbunke** [comment] 2017-10-17 12:49
Should the old version be updated or is an new v0.3.0 version enough? @IlkaCu @nesnoj @gplssm

**Comment by nesnoj** [comment] 2017-10-17 13:10
Uhh, that's not an easy question - is relates to the general question whether we should touch an existing dataset? I think we should not but (without a new release like 0.2.11). If yes, the bugfixes have to be documented somewhere. If not, document the bugs.

v0.3.0 is ok :+1:

**Comment by IlkaCu** [comment] 2018-02-06 13:33
@wolfbunke: What's the current status of this issue?

**Comment by wolfbunke** [comment] 2018-02-06 13:56
If we have a version documentation for the Data processing I just would add this information. Can you use my script below to check again if the problem appear in 0.3.0 and 0.3.1 (model_draft)? My server connection doesn't work for me at the moment.

**Comment by IlkaCu** [comment] 2018-02-06 14:02
The query only returns offshore wind power plants in voltage level 1. Seems that the problem does not occur in the current data set. Therefore I will close this issue.

**Closed by IlkaCu** 2018-02-06 14:02 UTC
Labels: bug
